### PR TITLE
Fix #8 - Add getKey() method

### LINKED ISSUE #8: Add a getKey() method to ScopeContext
This will allow to see if the scope is already running. This is different than the `isActive()` method because `scope()` can return the value of `inactiveScope()`

### PR DESCRIPTION
**Pull request by exabrial**
Fix #8 - Add getKey() method

### CODE REVIEW

**Comment by exabrial** [comment]
@dblevins I know you're a super busy guy and you have literally thousands of open source projects to manage along with navigating a company through a worldwide crisis :) If you're a bit tied up with other stuff, do you mind if I fork the project and release with the two PRs under another GAV?

**Comment by jgallimore** [comment]
I'll check it out today for you.

**Comment by jgallimore** [comment]
@exabrial I can release this - is there anything else I need to merge?

**Comment by exabrial** [comment]
Jonathan thank-you a ton! I don't there's anything else...

We have two custom scopes that are pretty useful: a BoundaryLayer and a ThreadScope we may push up after they've been in production for a bit longer and get the bugs worked out. This project made it pretty easy to develop them!

**Comment by jgallimore** [comment]
@exabrial no problem. I've released 0.4, so hopefully you're all good to go!

**Pull request merged**
